version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: who am i
          command: cat ~/.ssh/*
      - run:
          name: Print NodeJS version
          command: node --version
      - run:
          name: Install raml2html
          command: sudo npm install -g raml2html
      - run:
          name: Where is this running?
          command: pwd
      - run:
          name: Get a dir
          command: ls
      - run:
          name: Run raml2html
          command: raml2html ConnectionAPI.raml > ConnectionAPI.html
      - run:
          name: setup git user
          command: git config --global user.name "CircleCI automation"
      - run:
          name: setup git email
          command: git config --global user.email "nobody@example.com" 
      - run:
          name: git add
          command: git add ConnectionAPI.html
      - run:
          name: checkout master branch (change back to gh-pages)
          command: git checkout master
      - run:
          name: git commit
          command: git commit -m "Automated commit from CircleCI"
      - run:
          name: git push (change back to gh-pages)
          command: git push origin master
