version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Print NodeJS version
          command: node --version
      - run:
          name: Install raml2html
          command: sudo npm install -g raml2html
